MovieGoersII/ViewModels/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieGoersII.ViewModels
{
    public class SearchViewModel
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public ButtonTaskViewModel ButtonTask { get; set; }
    }
}

MovieGoersII/Controllers/MoviesControllers/MoviesDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersIIBL;

namespace MovieGoersII.Controllers.MoviesControllers
{
    public class MoviesDetailsController : Controller
    {
        IMoviesHandler _moviesHandler;
        ITmdbHandler _tmdbHandler;

        public MoviesDetailsController(IMoviesHandler moviesHandler, ITmdbHandler tmdbHandler)
        {
            _moviesHandler = moviesHandler;
            _tmdbHandler = tmdbHandler;
        }

        public async Task<IActionResult> DisplayMovies(int id)
        {
            Movies movie = await _moviesHandler.GetMovieByTmdbIdAsync(id);
            if(movie == null)
            {
                movie = await _tmdbHandler.MovieDetailsAsync(id);
            }
            return View(movie);
        }
    }
}

MovieGoersII/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersII.Handlers.UserCollectionHandler;
using MovieGoersII.ViewModels;
using MovieGoersIIBL;
using Newtonsoft.Json;

namespace MovieGoersII.Controllers
{
    public class SearchController : Controller
    {
        ITmdbHandler _handler;
        IUserCollectionHandler _collectionHandler;
        IMoviesHandler _moviesHandler;

        public SearchController(ITmdbHandler handler, IUserCollectionHandler collectionHandler, IMoviesHandler moviesHandler)
        {
            DotNetEnv.Env.Load();
            _handler = handler;
            _collectionHandler = collectionHandler;
            _moviesHandler = moviesHandler;
        }

        public IActionResult SearchMovies(SearchCriteriaViewModel searchCriteria)
        {
            return View(searchCriteria);
        }

        public async Task<IActionResult> SearchForMovies(string page, string searchQuery)
        {
            ViewBag.page = page;
            ViewBag.searchQuery = searchQuery;
            int userId = DotNetEnv.Env.GetInt("User_Id");
            var result = await _handler.MovieSearchListAsync(searchQuery, page);

            foreach(var item in result)
            {
                if(await _collectionHandler.CheckCollectionForMovieAsync(item.MovieId,userId))
                {
                    item.ButtonTask.Text = "-";
                    item.ButtonTask.Action = "RemoveFromCollection";
                    item.ButtonTask.Description = "Remove the movie from your collection";
                    item.ButtonTask.Controller = "Search";
                }
            }

            SearchCriteriaViewModel searchCriteriaViewModel = new SearchCriteriaViewModel
            {
                SearchModel = result.ToList()
            };
            
            return View("SearchMovies", searchCriteriaViewModel);
        }

        public async Task<IActionResult> AddToCollection(int id, string page, string searchQuery)
        {
            Movies movie = await _moviesHandler.GetMovieByTmdbIdAsync(id);

            if (movie == null)
            {
                var result = await _handler.MovieDetailsAsync(id);
                movie = await _moviesHandler.AddMovieToListAsync(result);
            }

            UserCollection collection = new UserCollection
            {
                MovieId = movie.Id,
                UserId = DotNetEnv.Env.GetInt("User_Id"),
                Rating = 4,
                Review = "Review Comments",
                IsSoftDeleted = false
            };

            await _collectionHandler.AddCollectionAsync(collection);
            return RedirectToAction("SearchForMovies", new { page = page, searchQuery = searchQuery });

        }

        public async Task<IActionResult> RemoveFromCollection(int id, string page, string searchQuery)
        {
            int userId = DotNetEnv.Env.GetInt("User_Id");
            var result = await _collectionHandler.RemoveCollectionAsync(id, userId);

            return RedirectToAction("SearchForMovies", new { page = page, searchQuery = searchQuery });
        }
    }
}

MovieGoersII/Controllers/SearchController/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersII.Handlers.UserCollectionHandler;
using MovieGoersII.ViewModels;
using MovieGoersIIBL;
using Newtonsoft.Json;

namespace MovieGoersII.Controllers
{

    /*
     * This class controls the functionalities such as
     * searching for a movie,
     * adding a movie to users' collection,
     * removing the movie from collection
     * and rendering the home page.
     */

    public class SearchController : Controller
    {
        readonly ITmdbHandler _handler;
        readonly IUserCollectionHandler _collectionHandler;
        readonly IMoviesHandler _moviesHandler;

        public SearchController(ITmdbHandler handler, IUserCollectionHandler collectionHandler, IMoviesHandler moviesHandler)
        {
            DotNetEnv.Env.Load(); //The API Key is currenly stored in a .env file.
            _handler = handler;
            _collectionHandler = collectionHandler;
            _moviesHandler = moviesHandler;
        }

        //Renders the home page that displays users' collection.
        public IActionResult SearchMovies(SearchCriteriaViewModel searchCriteria)
        {
            return View(searchCriteria);
        }


        //Searches for movies using the TMDB API.
        public async Task<IActionResult> SearchForMovies(string page, string searchQuery)
        {
            ViewBag.page = page;
            ViewBag.searchQuery = searchQuery;

            int userId = DotNetEnv.Env.GetInt("User_Id");

            var searchResult = await _handler.MovieSearchListAsync(searchQuery, page);

            ViewBag.totalPages = searchResult.Item2; //Item2 is the total number of pages the search result returns

            foreach (var item in searchResult.Item1) //Item1 is the list of movies returned by the TMDB handler method.
            {
                //Check if a movie is already in the collection. If yes, the button for removing the collection goes with the details.
                if(await _collectionHandler.CheckCollectionForMovieAsync(item.MovieId,userId))
                {
                    item.ButtonTask.Text = "-";
                    item.ButtonTask.Action = "RemoveFromCollection";
                    item.ButtonTask.Description = "Remove the movie from your collection";
                    item.ButtonTask.Controller = "Search";
                }
            }

            SearchCriteriaViewModel searchCriteriaViewModel = new SearchCriteriaViewModel
            {
                SearchModel = searchResult.Item1.ToList()
            };
            
            return View("SearchMovies", searchCriteriaViewModel);
        }


        //Adds movie to the users' collection using the TMDB Id for the movie.
        public async Task<IActionResult> AddToCollection(int id, string page, string searchQuery)
        {
            Movies movie = await _moviesHandler.GetMovieByTmdbIdAsync(id);

            // If the movie isn't already in the DB, fetch the details from the API and add it to the DB.
            if (movie == null)
            {
                var result = await _handler.MovieDetailsAsync(id);
                movie = await _moviesHandler.AddMovieToListAsync(result);
            }

            UserCollection collection = new UserCollection
            {
                MovieId = movie.Id,
                UserId = DotNetEnv.Env.GetInt("User_Id"),
                Rating = 4,
                Review = "Review Comments",
                IsSoftDeleted = false
            };

            await _collectionHandler.AddCollectionAsync(collection);

            //Redirect so that the same search page is displayed.
            return RedirectToAction("SearchForMovies", new { page = page, searchQuery = searchQuery });
        }


        //Removes the movie from users' collection.
        public async Task<IActionResult> RemoveFromCollection(int id, string page, string searchQuery)
        {
            int userId = DotNetEnv.Env.GetInt("User_Id");
            var result = await _collectionHandler.RemoveCollectionAsync(id, userId);

            //Redirect so that the same search page is displayed.
            return RedirectToAction("SearchForMovies", new { page = page, searchQuery = searchQuery });
        }
    }
}

MovieGoersII/ViewComponents/UserMovieCollectionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersII.Handlers.UserCollectionHandler;
using MovieGoersIIBL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieGoersII.ViewComponents
{
    public class UserMovieCollectionViewComponent: ViewComponent
    {
        IMoviesHandler _moviesHandler;
        IUserCollectionHandler _collectionHandler;
        public UserMovieCollectionViewComponent(IMoviesHandler moviesHandler, IUserCollectionHandler collectionHandler)
        {
            _moviesHandler = moviesHandler;
            _collectionHandler = collectionHandler;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetUsersMoviesAsync();
            return View(items);
        }

        public async Task<IEnumerable<Movies>> GetUsersMoviesAsync()
        {
            var collection = await _collectionHandler.GetCollectionByUserIdAsync(1);
            List<Movies> movies = new List<Movies>();
            foreach (var item in collection)
            {
                var res = await _moviesHandler.GetMovieByIdAsync(item.MovieId);
                Movies movie = new Movies
                {
                    TMDBId = res.TMDBId,
                    Title = res.Title
                };
                movies.Add(movie);
            }
            return movies;
        }
    }
}

MovieGoersII/Views/Search/SearchForMovies.cshtml
<!--
    This is the partial view responsible for
    displaying the search results returned by the
    TMDB API. 
-->

@model IEnumerable<MovieGoersII.ViewModels.SearchViewModel>
@{
    Layout = null;
}
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MovieId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MovieId)
                </td>
                <td>
                    @Html.ActionLink(item.MovieName, "DisplayMovies", "MoviesDetails", new { id = item.MovieId})
                </td>
                <td>
                    @Html.ActionLink(item.ButtonTask.Text, item.ButtonTask.Action, new { id = item.MovieId, page = ViewBag.page, searchQuery = ViewBag.searchQuery })
                </td>
            </tr>
        }
    </tbody>
</table>

<br />

<!-- Buttons to navigate to next and previous search pages-->
@if ((Convert.ToInt32(ViewBag.page) - 1) > 0)
    @Html.ActionLink("Previous", "SearchForMovies", new { page = Convert.ToInt32(ViewBag.page) - 1, searchQuery = ViewBag.searchQuery })

@if ((Convert.ToInt32(ViewBag.page) + 1) <= ViewBag.totalPages)
    @Html.ActionLink(" Next", "SearchForMovies", new{ page = Convert.ToInt32(ViewBag.page) + 1, searchQuery = ViewBag.searchQuery })

MovieGoersII/Views/Search/SearchMovies.cshtml
<!--
    This is the home page. It displays
    the users' collection, as well as 
    the search results for a movie.
-->

@model MovieGoersII.ViewModels.SearchCriteriaViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>View</title>
        
    </head>
    <body>
        <form method="get" asp-controller="Search" asp-action="SearchForMovies" id="search_form">
            <input type="hidden" asp-for="Page" id="page" value="1" />
            <input type="text" asp-for="SearchQuery" id="search_query" />
            <button type="submit" id="search_button" onclick="filter()">Search</button>
        </form>
        @{
            if (Model.SearchModel != null)
            {
                <!-- Display the search results as partial view -->
            <div>
                @await Html.PartialAsync("SearchForMovies", Model.SearchModel)
            </div>
            }
            else
            {
                <!-- Display the users' collection as a View-Component -->
                <div>
                    @await Component.InvokeAsync("UserMovieCollection")
                </div>
            }
        }
    

    </body>
</html>