MovieGoersII/ViewModels/RecommendationsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieGoersII.ViewModels
{
    public class RecommendationsViewModel
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int Intensity { get; set; }
        public int CharacterCentered { get; set; }
        public int Violence { get; set; }
        public int InformationRequired { get; set; }
        public int Pace { get; set; }
        public int SpecialEffects { get; set; }
        public int Suspense { get; set; }
            
        public List<SelectListItem> MoviesList { get; set; }
        
    }
}

MovieGoersII/Controllers/RecommendationsController/RecommendationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersII.Handlers.RecommendationHandler;
using MovieGoersII.Handlers.UserCollectionHandler;
using MovieGoersII.ViewModels;
using MovieGoersIIBL;

namespace MovieGoersII.Controllers.RecommendationsController
{
    public class RecommendationsController : Controller
    {
        IRecommendationsHandler _recommendationsHandler;
        IMoviesHandler _moviesHandler;
        IUserCollectionHandler _collectionHandler;

        public RecommendationsController(IRecommendationsHandler recommendationsHandler, IMoviesHandler moviesHandler, IUserCollectionHandler collectionHandler)
        {
            _recommendationsHandler = recommendationsHandler;
            _moviesHandler = moviesHandler;
            _collectionHandler = collectionHandler;
        }


        public async Task<IActionResult> UserRecommendations()
        {
            Recommendations recommendationsInit;
            
            var movieRatings = await _recommendationsHandler.GetRecommendationRatingsAsync();
            var res = await _collectionHandler.GetCollectionByUserIdAsync(1);
            int rateParameter = 0;
            List<Movies> userMovies = new List<Movies>();

            foreach(var item in res.ToList())
            {
                userMovies.Add(await _moviesHandler.GetMovieByIdAsync(item.MovieId));
            }

            List<Movies> recommendedMovies = new List<Movies>();
            
            
            foreach(var userMovie in userMovies.Where(o => o.IsAdminRated))
            {
                recommendationsInit = await _recommendationsHandler.GetRecommendationRatingsByMovieIdAsync(userMovie.Id);

                foreach (var item in movieRatings.Where(o => o.Id != recommendationsInit.Id))
                {
                    rateParameter = 0;
                    if (Math.Abs(item.InformationRequired - recommendationsInit.InformationRequired) <= 1)
                    {
                        rateParameter += item.InformationRequired == recommendationsInit.InformationRequired ? 2 : 1;
                    }
                    if (Math.Abs(item.SpecialEffects - recommendationsInit.SpecialEffects) <= 1)
                    {
                        rateParameter += item.SpecialEffects == recommendationsInit.SpecialEffects ? 2 : 1;
                    }
                    if (Math.Abs(item.Suspense - recommendationsInit.Suspense) <= 1)
                    {
                        rateParameter += item.Suspense == recommendationsInit.Suspense ? 2 : 1;
                    }
                    if (Math.Abs(item.Intensity - recommendationsInit.Intensity) <= 1)
                    {
                        rateParameter += item.Intensity == recommendationsInit.Intensity ? 2 : 1;
                    }
                    if (Math.Abs(item.Pace - recommendationsInit.Pace) <= 1)
                    {
                        rateParameter += item.Pace == recommendationsInit.Pace ? 2 : 1;
                    }
                    if (Math.Abs(item.Violence - recommendationsInit.Violence) <= 1)
                    {
                        rateParameter += item.Violence == recommendationsInit.Violence ? 2 : 1;
                    }


                    if (!res.ToList().Where(o => o.MovieId == item.MovieId).Any() 
                            && rateParameter >= 10
                            && !recommendedMovies.ToList().Where(m => m.Id == item.MovieId).Any())
                    {
                        recommendedMovies.Add(await _moviesHandler.GetMovieByIdAsync(item.MovieId));
                    }
                }
            }
            
            return View(recommendedMovies);
        }

        public async Task<IActionResult> AddRatingsPage()
        {
            var movies = await _moviesHandler.GetMoviesByStatusAsync(0);
            List<SelectListItem> moviesSelectList = new List<SelectListItem>();
            SelectListItem movieItem;
            movies.ToList().ForEach(item =>
            {
                movieItem = new SelectListItem();
                movieItem.Text = item.Title;
                movieItem.Value = Convert.ToString(item.Id);
                moviesSelectList.Add(movieItem);
            });
            
            return View(new RecommendationsViewModel { MoviesList = moviesSelectList});
        }

        public async Task<IActionResult> AddRecommendationRatings(RecommendationsViewModel recommendations)
        {
            Recommendations recommendationRatings = new Recommendations
            {
                MovieId = recommendations.MovieId,
                Intensity = recommendations.Intensity,
                InformationRequired = recommendations.InformationRequired,
                Suspense = recommendations.Suspense,
                SpecialEffects = recommendations.SpecialEffects,
                CharacterCentered = recommendations.CharacterCentered,
                Pace = recommendations.Pace,
                Violence = recommendations.Violence
            };

            var result = await _recommendationsHandler.PostRecommendationsAsync(recommendationRatings);

            if(result != null)
            {
                var movie = await _moviesHandler.GetMovieByIdAsync(recommendationRatings.MovieId);
                movie.IsAdminRated = true;

                var res = await _moviesHandler.EditMovieStatusAsync(movie);
            }

            return RedirectToAction("AddRatingsPage");

        }
    }
}

MovieGoersII/Views/Recommendations/AddRatingsPage.cshtml
@model MovieGoersII.ViewModels.RecommendationsViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRatingsPage</title>
</head>
    <body>

        <form asp-controller="Recommendations" asp-action="AddRecommendationRatings" method="post">
            <select asp-for="MovieId" asp-items="Model.MoviesList"></select>
            <input asp-for="InformationRequired" />
            <input asp-for="Suspense" />
            <input asp-for="Violence" />
            <input asp-for="SpecialEffects" />
            <input asp-for="Intensity" />
            <input asp-for="Pace" />
            <input asp-for="CharacterCentered" />
            <br /><button type="submit">Register</button>
        </form>

    </body>
</html>

MovieGoersII/Views/Recommendations/UserRecommendations.cshtml
@model IEnumerable<MovieGoersIIBL.Movies>

    @{
        Layout = null;
    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>UserRecommendations</title>
    </head>
    <body>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Image)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Genre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TMDBId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IMDBId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Overview)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Language)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReleaseDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Runtime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsAdminRated)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Image)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Genre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TMDBId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IMDBId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Language)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReleaseDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Runtime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsAdminRated)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </body>
</html>