MovieGoersII/Controllers/MoviesControllers/MoviesDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers;
using MovieGoersII.Handlers.MoviesHandler;
using MovieGoersIIBL;

namespace MovieGoersII.Controllers.MoviesControllers
{
    public class MoviesDetailsController : Controller
    {
        IMoviesHandler _moviesHandler;
        ITmdbHandler _tmdbHandler;

        public MoviesDetailsController(IMoviesHandler moviesHandler, ITmdbHandler tmdbHandler)
        {
            _moviesHandler = moviesHandler;
            _tmdbHandler = tmdbHandler;
        }

        public async Task<IActionResult> DisplayMovies(int id)
        {
            Movies movie = await _moviesHandler.GetMovieByTmdbIdAsync(id);
            if(movie == null)
            {
                movie = await _tmdbHandler.MovieDetailsAsync(id);
            }
            return View(movie);
        }
    }
}

MovieGoersII/ViewComponents/UserReviewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieGoersII.Handlers.UserCollectionHandler;
using MovieGoersII.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieGoersII.ViewComponents
{
    public class UserReviewsViewComponent: ViewComponent
    {
        IUserCollectionHandler _collectionhandler;

        public UserReviewsViewComponent(IUserCollectionHandler collectionhandler)
        {
            _collectionhandler = collectionhandler;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var reviews = await GetReviewsAsync(id);
            return View(reviews);
        }

        public async Task<IEnumerable<ReviewsViewModel>> GetReviewsAsync(int movieId)
        {
            var res = _collectionhandler.GetMovieReviewsFromId(movieId);
            List<ReviewsViewModel> reviewsModels = new List<ReviewsViewModel>();
            ReviewsViewModel review;


            await foreach (var item in res)
            {
                review = new ReviewsViewModel
                {
                    UserName = item.User.UserName,
                    MovieId = item.MovieId,
                    Rating = item.Rating,
                    Review = item.Review
                };

                reviewsModels.Add(review);
            }

            return reviewsModels;
        }

    }
}

MovieGoersII/Views/MoviesDetails/DisplayMovies.cshtml
@model MovieGoersIIBL.Movies

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DisplayMovies</title>
</head>
<body>

<div>
    <h4>Movies</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TMDBId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TMDBId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IMDBId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IMDBId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Overview)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Overview)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdminRated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdminRated)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    @await Component.InvokeAsync("UserReviews", new { id = Model.Id })
</div>
</body>
</html>